name: JamiesonHill
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49752
title: Jamieson Hill
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12151e'
    - '#2e3748'
    - '#455971'
    - '#7694ac'
    - '#adc7de'
  brandStrength: 0.8125
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
