name: JamiesonHill
favicon: null
layout_spectrum: 0.1774193
typography_spectrum: 0.9172902
title: Jamieson Hill
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BCAEAD'
    - '#170E0C'
    - '#877877'
    - '#424B65'
    - '#BD0D30'
  brandStrength: 0.7849463
  lightness: 0.6546959
  saturation: 0.2386199
  rhythmicContrast: 0.5710464
purpose: []
