name: JamiesonHill
favicon: null
layout_spectrum: 0.88117
typography_spectrum: 0.04332
title: Jamieson Hill
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#12151e'
    - '#2e3748'
    - '#455971'
    - '#7694ac'
    - '#adc7de'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
