name: JamiesonHill
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49752
title: Jamieson Hill
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BCAEAD'
    - '#170E0C'
    - '#877877'
    - '#424B65'
    - '#BD0D30'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
