name: JamiesonHill
favicon: null
layout_spectrum: 0.88117
typography_spectrum: 0.04332
title: Jamieson Hill
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-5939329-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#16202c'
    - '#31475c'
    - '#577a8e'
    - '#8eb0c9'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
